spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auto-apply-service
      auto-offset-reset: earliest
    producer:
      acks: all
