package com.save_help.Save_Help.dailyNecessities.service;

import com.save_help.Save_Help.dailyNecessities.dto.RequestReasonResponseDto;
import com.save_help.Save_Help.dailyNecessities.entity.UserNecessityRequest;
import com.save_help.Save_Help.dailyNecessities.repository.UserNecessityRequestRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Service
@RequiredArgsConstructor
public class DailyNecessitiesRequestService {

    private final UserNecessityRequestRepository requestRepository;

    public RequestReasonResponseDto getRequestReason(Long requestId) {

        UserNecessityRequest request = requestRepository.findById(requestId)
                .orElseThrow(() -> new IllegalArgumentException("신청 내역을 찾을 수 없습니다."));

        Long userId = request.getUser().getId();
        Long itemId = request.getItem().getId();

        LocalDateTime created = request.getCreatedAt();
        LocalDateTime sevenDaysAgo = created.minusDays(7);

        // 최근 7일간 동일 카테고리 사용량 분석
        var recentRequests = requestRepository
                .findByUser_IdAndCreatedAtAfter(userId, sevenDaysAgo);

        long sameCategoryCount = recentRequests.stream()
                .filter(r -> r.getItem().getCategory() == request.getItem().getCategory())
                .count();

        String reason;

        if (request.isAutoGenerated()) {
            reason = String.format(
                    "사용자가 설정한 자동 재신청(interval: %d일)에 따라 생성된 요청입니다.",
                    request.getAutoIntervalDays()
            );
        }

        else if (sameCategoryCount >= 7) {
            reason = String.format(
                    "최근 7일 동안 '%s' 카테고리의 사용량이 높아 재신청이 발생했습니다.",
                    request.getItem().getCategory().name()
            );
        }
        // 유통기한 임박 관련 요청 (예: 식료품/위생용품)
        else if (request.getItem().getExpirationDate() != null &&
                request.getItem().getExpirationDate().isBefore(LocalDate.now().plusDays(7))) {
            reason = "해당 품목의 유통기한이 임박하여 재신청이 필요합니다.";
        }
        // 단순 사용자 직접 신청
        else {
            reason = "사용자가 직접 신청한 요청입니다.";
        }

        return new RequestReasonResponseDto(requestId, userId, itemId, reason);
    }

}
